---
name: Deploy to AWS

on:
  release:
    types: [created]

jobs:
  deploy_to_aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: sam build --use-container
      - run: |
          sam deploy --config-env the_cat_assignment --parameter-overrides \
          OmdbApiSecretKey=${{ secrets.OMDB_API_SECRET_KEY }}
